In [1]:
import numpy as np
import pandas as pd

In [2]:
print('Task 1')

# Wczytanie danych
data = pd.read_csv('data/01/Zadanie_1.csv', delimiter=';')
matrix = data.to_numpy()

# a) Liczba komórek w macierzy
print('Dane podstawowe bez obróbki')
print('\tLiczba komórek:  ', matrix.size)

# b) Liczba wierszy i kolumn
print('\tLiczba wierszy:  ', matrix.shape[0])
print('\tLiczba kolumn:   ', matrix.shape[1])

# c) Statystyki opisowe dla pełnych danych (z NaN w macierzy)
print('\tŚrednia:         ', np.mean(matrix))
print('\tMediana:         ', np.median(matrix))
print('\tWariancja:       ', np.var(matrix))

# d) Usunięcie braków danych - maskowanie NaN
# Oba zapisy dają taki sam wynik ale ten drugi był na wykładach
# mask = ~np.isnan(matrix)
# masked_matrix = matrix[mask]
# print('Pominięcie brakujących danych (usunięcie NaN)')
# print('\tŚrednia:         ', np.mean(masked_matrix))
# print('\tMediana:         ', np.median(masked_matrix))
# print('\tWariancja:       ', np.var(masked_matrix))

masked_matrix = np.ma.masked_invalid(matrix)
print(masked_matrix)
print('Pominięcie brakujących danych (maskowanie NaN)')
print('\tŚrednia:         ', np.ma.mean(masked_matrix))
print('\tMediana:         ', np.ma.median(masked_matrix))
print('\tWariancja:       ', np.ma.var(masked_matrix))

Task 1
Dane podstawowe bez obróbki
	Liczba komórek:   960
	Liczba wierszy:   60
	Liczba kolumn:    16
	Średnia:          nan
	Mediana:          nan
	Wariancja:        nan
[[36.0 27.0 71.0 8.1 3.34 11.4 81.5 3243.0 8.8 42.6 11.7 21.0 -- 59.0
  59.0 921.87]
 [35.0 23.0 72.0 11.1 3.14 11.0 78.8 4281.0 3.6 50.7 14.4 8.0 10.0 39.0
  57.0 997.875]
 [44.0 29.0 74.0 10.4 3.21 9.8 81.6 4260.0 0.8 39.4 -- 6.0 6.0 33.0 54.0
  962.354]
 [47.0 45.0 79.0 6.5 3.41 11.1 77.5 3125.0 27.1 50.2 20.6 18.0 8.0 24.0
  56.0 982.291]
 [43.0 35.0 77.0 7.6 3.44 9.6 84.6 6441.0 24.4 43.7 14.3 43.0 38.0 --
  55.0 1071.289]
 [53.0 45.0 80.0 7.7 3.45 10.2 66.8 3325.0 38.5 43.1 25.5 30.0 32.0 72.0
  54.0 1030.38]
 [43.0 30.0 74.0 10.9 3.23 12.1 83.9 4679.0 3.5 49.2 11.3 21.0 32.0 62.0
  56.0 934.7]
 [45.0 30.0 73.0 9.3 3.29 10.6 86.0 2140.0 5.3 40.4 10.5 6.0 4.0 4.0 56.0
  899.529]
 [36.0 24.0 70.0 9.0 3.31 10.5 83.2 6582.0 8.1 42.5 12.6 18.0 12.0 37.0
  61.0 1001.902]
 [36.0 27.0 72.0 9.5 3.36 10.7 79.3 4213.0 6.7 

In [3]:
print('Task 2')
data = np.loadtxt('data/01/Zadanie_2.csv', delimiter=';')
eigenvalues, eigenvectors = np.linalg.eig(data)

print('\n================== Wartości własne ==================\n', eigenvalues)
print('\n================== Wektory własne ===================\n', eigenvectors)
print('\n================== Macierz odwrotna ================\n', np.linalg.inv(data))

Task 2

================== Wartości własne ==================
 [104.34960192 +0.j         -23.35660516+18.84992811j
 -23.35660516-18.84992811j  15.92989017 +0.j
  -4.99456452 +0.j           0.35205717 +5.80125175j
   0.35205717 -5.80125175j  -1.03383491 +0.j
   3.87900166 +1.42651533j   3.87900166 -1.42651533j]

================== Wektory własne ===================
 [[-0.29000475+0.j         -0.07545445+0.07743149j -0.07545445-0.07743149j
  -0.03544485+0.j          0.42681634+0.j         -0.22172831-0.29869259j
  -0.22172831+0.29869259j  0.41343726+0.j         -0.28670255+0.21891569j
  -0.28670255-0.21891569j]
 [-0.24163153+0.j          0.41229621+0.09197324j  0.41229621-0.09197324j
   0.45873475+0.j         -0.27056206+0.j         -0.01331344+0.1422557j
  -0.01331344-0.1422557j  -0.31591047+0.j          0.41954481-0.10561864j
   0.41954481+0.10561864j]
 [-0.41060573+0.j          0.37509638-0.00960818j  0.37509638+0.00960818j
   0.64067986+0.j         -0.37967609+0.j         -0.6052523

In [4]:
print('Task 3')

A = np.loadtxt('data/01/Zadanie_3_macierz_A.csv', delimiter=',')
B = np.loadtxt('data/01/Zadanie_3_macierz_B.csv', delimiter=',')

def csm(a, b):
    num=np.dot(a, b.T)
    p1= np.sqrt(np.sum(a ** 2, axis=1))[:, np.newaxis]
    p2= np.sqrt(np.sum(b ** 2, axis=1))[np.newaxis, :]
    return num/(p1*p2)

similarity = csm(A,B)
print(similarity)

Task 3
[[0.7970534  0.93075784 0.85152689 0.80479273 0.86772183]
 [0.3985267  0.56879646 0.57428557 0.32694705 0.97618706]
 [0.92108283 0.9763075  0.91890016 0.9336035  0.69421013]]
